apiVersion: batch/v1
kind: Job
metadata:
  name: astra-manage-app
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  template:
    spec:
      volumes:
        - name: astra-control-config
          secret:
            secretName: astra-control-config
      containers:
      - name: alpine-actoolkit
        image: alpine:latest
        command: ["/bin/sh"]
        args:
        - -c
        - >
          APPNAME=wordpress &&
          apk add py3-pip jq &&
          python3 -m pip install --upgrade pip &&
          python3 -m pip install actoolkit &&
          for i in `actoolkit -o json list apps -u -s namespace -n $APPNAME | jq -r '.items[].id'`;
          do
            echo actoolkit: managing app $APPNAME / $i;
            actoolkit manage app $i;
            sleep 5;
            echo actoolkit: creating protection policy for $APPNAME / $i;
            actoolkit create protectionpolicy $i -g hourly  -m 0      -b 1 -s 1;
            actoolkit create protectionpolicy $i -g daily   -H 0      -b 2 -s 2;
            actoolkit create protectionpolicy $i -g weekly  -H 0 -W 1 -b 2 -s 2;
            actoolkit create protectionpolicy $i -g monthly -H 0 -M 1 -b 2 -s 2;
          done;
        volumeMounts:
          - mountPath: /etc/astra-toolkits
            name: astra-control-config
            readOnly: true
      restartPolicy: Never
  backoffLimit: 1
